### PR TITLE
Add missing copyright notices to scripts

### PR DESCRIPTION
**Pull request by hariso**
### Description

Adds missing copyright notices to scripts.

### Quick checks

- [ ] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [ ] There is no other [pull request](https://github.com/ConduitIO/conduit/pulls) for the same update/change.
- [ ] I have written unit tests.
- [ ] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

**Comment by lovromazgon** [comment]
Given that this will be hosted on `conduit.io` I would move the PR to [ConduitIO/conduit-site](https://github.com/ConduitIO/conduit-site) - wdyt @ConduitIO/conduit-core?

**Comment by lovromazgon** [comment]
I don't see a need for it here tbh, it's not a script that helps us during developing Conduit, so conduit-site seems more appropriate to me. And we spare the user from a redirect 🙂

**Comment by hariso** [comment]
I've just repurposed the PR to add the missing copyright notices. The installation script is now here: https://github.com/ConduitIO/conduit-site/pull/169.

**Review by lovromazgon — APPROVED** [review]
I like the attention to detail, I see you actually figured out the year of the file creation 😄

**Pull request merged**
