### PR TITLE
Print splash when Conduit starts

### PR DESCRIPTION
**Pull request by lovromazgon**
### Description

This is something I played with yesterday during Champagne day. It displays an ASCII logo when Conduit starts as well as the version and os/arch info. I picked 3 options that turned out looking best, we have to decide which one we want to display (if any).

Option 1:
```
        __________
       /          \
  ____/    ____    \____
 /        /    \        \
 \____    \____/    ____/
      \            /
       \__________/      Conduit v0.2.0-nightly.20220224-1-g1f7b9bc darwin/amd64
```

Option 2:
```
             ....
         .::::::::::.
       .:::::‘‘‘‘:::::.
      .::::        ::::.
 .::::::::          ::::::::.
 `::::::::          ::::::::‘
      `::::        ::::‘
       `:::::....:::::‘
         `::::::::::‘
             ‘‘‘‘            Conduit v0.2.0-nightly.20220224-1-g1f7b9bc darwin/amd64
```

Option 3:
```
            &BGGPPGB#&
         #PJ??????????YG&
       &5????J5PGGPY?????G
      #J???Y#       &G????P
 GYJJJ????J&          G????JJJJ5&
 P????????Y           B????????J#
     &B????P&        #J???Y#
       BJ????5GB##BPY????5&
        &GJ????????????5B
           #BP5YYY55GB&          Conduit v0.2.0-nightly.20220224-1-g1f7b9bc darwin/amd64
```

### CODE REVIEW

**Comment by hariso** [comment]
Option 2 : )

**Comment by justmisosoup** [comment]
Throwing my hat in for **Option 2**.

**Comment by lovromazgon** [comment]
I see that the majority prefers option 2, so I removed the other two. Here's how it looks like now:
image

**Review by maha-hajja — APPROVED** [review]
Looks amazing!

**Pull request merged**
